Update GitHub actions

diff --git a/.github/workflows/style-check.yml b/.github/workflows/style-check.yml
--- a/.github/workflows/style-check.yml
+++ b/.github/workflows/style-check.yml
@@ -1,4 +1,4 @@
-name: ClangFormat
+name: Code formatting
 
 on:
   push:
@@ -7,32 +7,36 @@ on:
 
 jobs:
   check:
-    runs-on: ubuntu-20.04
+    name: ClangFormat
+
+    runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
-      - name: Download a recent, static build of clang-format
-        run: |
-          wget --no-verbose https://github.com/angular/clang-format/raw/master/bin/linux_x64/clang-format
-          chmod a+x clang-format
-      - name: Print clang-format version
-        run: |
-          ./clang-format --version
+      - uses: actions/checkout@v4
+
+      - name: Install clang-format
+        run: sudo apt install clang-format
+
       - name: Run clang-format and report result
         run: |
-          cd src      
-          # Parse full lines
-          export IFS=$'\n'
-          # For each file in repository with name ending with ".hpp", ".h", ".cpp" ...
-          for file in $(git ls-files | egrep "\\.hpp$|\\.h$|\\.cpp$"$); do
-              echo Formatting "$file"
-              # format it in place, so git can pick it up.
-              ../clang-format -style=file -i "$file"
+          declare -a directories=("src" "include" "tests")
+          for directory in "${directories[@]}"; do
+            (
+              cd ${directory}
+              # Parse full lines
+              export IFS=$'\n'
+              # For each file in repository with name ending with ".hpp", ".h", ".cpp" ...
+              for file in $(git ls-files | egrep "\\.hpp$|\\.h$|\\.cpp$"$); do
+                  echo Formatting "$file"
+                  # format it in place, so git can pick it up.
+                  ../clang-format -style=file -i "$file"
+              done
+            )
+            # Just some visual separation
+            echo -e "\\n\\n\\n\\tChecking diff...\\n\\n\\n"
+            # Set error mode. Makes bash bail on first non-zero exit code
+            set -e
+            # Print diff, if any and report with exit code.
+            git diff --exit-code
+            # When no diff present, provide status.
+            echo -e "\\tStyle is fine"
           done
-          # Just some visual separation
-          echo -e "\\n\\n\\n\\tChecking diff...\\n\\n\\n"
-          # Set error mode. Makes bash bail on first non-zero exit code
-          set -e
-          # Print diff, if any and report with exit code.
-          git diff --exit-code
-          # When no diff present, provide status.
-          echo -e "\\tStyle is fine"
